############################
##### Overall workflow #####
############################

# Type of input data (either 'Single' or 'Cohort')
DATA: ""

# File directories to reference genome and dbSNP database
REFGENOME: ""
dbSNP: ""

# Temporary file directory
TEMPDIR: ""

# WES settings (leave blank if analysing other data such as WGS)
WES:
  # Genomic intervals over which to operate
  INTERVALS: ""
  # Padding (in bp) to add to each interval
  PADDING: ""

##############################
##### Base recalibration #####
##############################

# Resources used for base recalibration
RECALIBRATION:
  RESOURCES: ""